version: '2'
networks:
  vault-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/16
          ip_range: 172.42.10.0/24
          gateway: 172.42.10.254

services:
  consult-srv1:
    hostname: consult-srv1
    image: consul
    command: agent -server -bootstrap-expect 3 -bind 172.42.10.1
    networks:
      vault-net:
        ipv4_address: 172.42.10.1

  consult-srv2:
    hostname: consult-srv2
    image: consul
    command: agent -server -retry-join 172.42.10.1 -bind 172.42.10.2
    depends_on:
      - consult-srv1
    networks:
      vault-net:
        ipv4_address: 172.42.10.2

  consult-srv3:
    hostname: consult-srv3
    image: consul
    command: agent -server -retry-join 172.42.10.1 -bind 172.42.10.3
    depends_on:
      - consult-srv2
    networks:
      vault-net:
        ipv4_address: 172.42.10.3

  consult-client1:
    hostname: consult-client1
    image: consul
    command: agent -client=0.0.0.0 -ui -retry-join 172.42.10.1 -bind 172.42.10.10
    depends_on:
      - consult-srv3
    ports:
      - "18500:8500"
    networks:
      vault-net:
        ipv4_address: 172.42.10.10

  consult-client2:
    hostname: consult-client2
    image: consul
    command: agent -client=0.0.0.0 -ui -retry-join 172.42.10.1 -bind 172.42.10.11
    depends_on:
      - consult-srv3
    ports:
      - "18501:8500"
    networks:
      vault-net:
        ipv4_address: 172.42.10.11

  vault1:
    hostname: vault-server1
    image: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./configs/vault/vault-server1.hcl:/vault/config/local.hcl
    networks:
      vault-net:
        ipv4_address: 172.42.10.5
    depends_on:
      - consult-client1
    command: server

  vault2:
    hostname: vault-server2
    image: vault
    ports:
      - "9200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./configs/vault/vault-server2.hcl:/vault/config/local.hcl
    networks:
      vault-net:
        ipv4_address: 172.42.10.6
    depends_on:
      - consult-client2
    command: server

## Telemetry

  prometheus:
      image: prom/prometheus
      volumes:
      - ./configs/prometheus/:/etc/prometheus/
      #- prometheus_data:/var/lib/prometheus
      restart: always
      links:
        - cadvisor:cadvisor
        - node-exporter:node-exporter
      networks:
        vault-net:
          ipv4_address: 172.42.10.20
      ports:
        - 9090:9090  

  node-exporter:
    image: quay.io/prometheus/node-exporter
    hostname: node-exporter
    volumes:
      - /proc:/usr/proc
      - /sys:/usr/sys
      - /:/rootfs
    networks:
      vault-net:
        ipv4_address: 172.42.10.21
    ports:
      - 9100:9100

  cadvisor:
    image: google/cadvisor
    hostname: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      vault-net:
        ipv4_address: 172.42.10.22
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana
    container_name: grafana
    #volumes:
    #  - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    env_file:
      - grafana.config
    depends_on:
      - prometheus      
    networks:
      vault-net:
        ipv4_address: 172.42.10.23  

## Clients
  ubuntu-ssh:
    image: wilton/ubuntu-ssh
    container_name: ubuntu-ssh
    ports:
      - "22:22"
    networks:
      vault-net:
        ipv4_address: 172.42.10.50  


#volumes:
#    prometheus_data:
#    grafana_data:    
